[general]
enable_bucket = true
caption_extension = ".txt"

[[datasets]]
resolution = [512, 512]
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = "E:/新建文件夹/When the Sword Arrives/game/training/identity_lock/data/lbp"
  num_repeats = 10
